extends Node

## The single point of network contact for the whole mod.
##
## Nothing else may make an HTTP call. That is not tidiness -- it is what makes
## the spec's transport fallback cheap: if in-mod HTTP ever stops working, this
## file is the only one that changes.
##
## Responsibilities: auth header, timeouts, retry with backoff, idempotency
## keys, rate-limit handling, and online/offline detection.
##
## Explicitly NOT its responsibility: deciding what anything means. It returns
## what the server said. Interpreting a phase-2 `status` field, computing a
## price, or choosing whether a trade is sound all happen elsewhere -- and the
## price never happens at all, because the server sends it.

signal online_changed(is_online: bool)

const LOG_PREFIX := "[FleaMarket/net] "

const DEFAULT_BASE_URL := "https://api.domfragsvostokmods.bid/v1"

## Whole-transfer budget. HTTPRequest.timeout covers the entire transfer rather
## than just connect/stall, so this has to be generous enough for the largest
## body we ask for -- the catalog runs ~100KB.
const REQUEST_TIMEOUT := 20.0
const BODY_LIMIT := 8 * 1024 * 1024

## Retry budget. Deliberately small: a player standing at a terminal would
## rather see an honest "offline" than watch a spinner for a minute.
const MAX_ATTEMPTS := 3
const BACKOFF_BASE_SECONDS := 0.6
const BACKOFF_MAX_SECONDS := 6.0
## A concurrent duplicate of the same idempotency key is still resolving. The
## server tells us to come back shortly with the SAME key.
const IDEMPOTENCY_RETRY_SECONDS := 1.2
## Cap on how long we will sit waiting out a 429 before giving up and reporting
## offline. Rate limits are 240 reads/min, so a human never sees this.
const RATE_WAIT_MAX_SECONDS := 10.0

var base_url: String = DEFAULT_BASE_URL
var player_key: String = ""

var _online := true
var _consecutive_transport_failures := 0
var _crypto: Crypto = null


func _ready() -> void:
	_crypto = Crypto.new()


func configure(url: String, key: String) -> void:
	if url != "":
		base_url = url.rstrip("/")
	player_key = key


func is_online() -> bool:
	return _online


func has_key() -> bool:
	return player_key.strip_edges() != ""


# --- Public API ---

## GET. `query` is an optional {String: Variant} of query parameters; values are
## URI-encoded here so callers never hand-build a query string.
func get_json(path: String, query: Dictionary = {}) -> Dictionary:
	return await _send("GET", path + _build_query(query), "", "")


## POST with a client-generated idempotency key.
##
## The key is REQUIRED and must be generated by the caller, not here. It has to
## be written into PendingLedger and persisted BEFORE anything is destroyed, and
## replayed with the same value on recovery -- so its lifetime is longer than
## this call and it cannot be minted inside it.
func post_json(path: String, body: Dictionary, idempotency_key: String) -> Dictionary:
	if idempotency_key.strip_edges() == "":
		push_error("FleaMarket: post_json called without an idempotency key")
		return _failure("missing_idempotency_key",
			"Refusing to send a mutating call with no idempotency key.")

	var payload := body.duplicate(true)
	payload["idempotency_key"] = idempotency_key
	return await _send("POST", path, JSON.stringify(payload), idempotency_key)


## DELETE, and any other verb that carries no body.
##
## Cancelling a listing is the only current caller. It is mutating but has no
## ordering hazard: nothing is destroyed client-side, the server unwinds its own
## escrow and schedules the item back as an ordinary delivery. So it takes an
## idempotency key like any mutating call, but needs no PendingLedger entry --
## there is no window in which a crash could lose anything.
func request_json(method: String, path: String, idempotency_key: String,
		query: Dictionary = {}) -> Dictionary:
	if idempotency_key.strip_edges() == "":
		push_error("FleaMarket: request_json called without an idempotency key")
		return _failure("missing_idempotency_key",
			"Refusing to send a mutating call with no idempotency key.")
	return await _send(method, path + _build_query(query), "", idempotency_key)


## Fresh RFC-4122 v4 UUID for use as an idempotency key.
func new_idempotency_key() -> String:
	var b: PackedByteArray
	if _crypto != null:
		b = _crypto.generate_random_bytes(16)
	else:
		b = PackedByteArray()
		b.resize(16)
		for i in range(16):
			b[i] = randi() % 256
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	var h := b.hex_encode()
	return "%s-%s-%s-%s-%s" % [
		h.substr(0, 8), h.substr(8, 4), h.substr(12, 4), h.substr(16, 4), h.substr(20, 12)
	]


# --- Core send loop ---

func _send(method: String, path: String, body: String, idempotency_key: String) -> Dictionary:
	var attempt := 0

	while true:
		attempt += 1
		var res := await _send_once(method, path, body, idempotency_key)

		# --- Transport failure: no HTTP response at all ---
		if not res["transport_ok"]:
			if attempt < MAX_ATTEMPTS:
				await _sleep(_backoff(attempt))
				continue
			_note_transport_failure()
			return _failure("offline",
				"Could not reach the market. %s" % res.get("detail", ""))

		# We got bytes back, so the network is alive regardless of status code.
		_note_transport_success()

		var code: int = res["code"]

		# --- 429: honour the server's stated wait ---
		if code == 429:
			var wait := _rate_limit_wait(res["headers"])
			if attempt < MAX_ATTEMPTS and wait <= RATE_WAIT_MAX_SECONDS:
				_log("rate limited, waiting %.1fs" % wait)
				await _sleep(wait)
				continue
			return _failure("rate_limited",
				"The market is rate limiting us. Try again in a moment.", code, res)

		# --- 409 idempotency_retry: same key, shortly ---
		# Never mint a new key here. A duplicate of this exact operation is
		# mid-flight; a fresh key would perform the action a second time.
		if code == 409 and _error_code(res) == "idempotency_retry":
			if attempt < MAX_ATTEMPTS:
				_log("idempotency_retry for %s, retrying same key" % idempotency_key)
				await _sleep(IDEMPOTENCY_RETRY_SECONDS)
				continue
			return _failure("idempotency_retry",
				"A duplicate of this request is still resolving.", code, res)

		# --- 5xx: transient server fault ---
		if code >= 500:
			if attempt < MAX_ATTEMPTS:
				await _sleep(_backoff(attempt))
				continue
			return _failure("server_error",
				"The market had an internal error.", code, res)

		# --- 401/403: a retry cannot fix a bad key ---
		if code == 401 or code == 403:
			return _failure("unauthorized",
				"This player key was rejected by the market.", code, res)

		# --- Other 4xx: our fault, deterministic, never retry ---
		if code >= 400:
			return _failure(_error_code(res),
				_error_message(res), code, res)

		# --- Success ---
		return {
			"ok": true,
			"code": code,
			"json": res["json"],
			"headers": res["headers"],
			"elapsed_ms": res["elapsed_ms"],
			"error": "",
			"message": "",
		}

	# Unreachable; GDScript wants a return on every path.
	return _failure("unknown", "Request loop exited unexpectedly.")


func _send_once(method: String, path: String, body: String,
		idempotency_key: String = "") -> Dictionary:
	var tree := get_tree()
	if tree == null:
		return {
			"transport_ok": false, "code": 0, "json": null, "headers": [],
			"elapsed_ms": 0, "detail": "No scene tree.",
		}

	var req := HTTPRequest.new()
	req.timeout = REQUEST_TIMEOUT
	# Godot 4.6 calls this body_size_limit; download_body_size_limit was the 3.x
	# name and silently fails to assign, leaving the cap off entirely.
	req.body_size_limit = BODY_LIMIT
	add_child(req)

	var headers := [
		"Accept: application/json",
		"User-Agent: vostok-flea-market/%s" % _mod_version(),
	]
	if has_key():
		headers.append("Authorization: Bearer " + player_key)
	if body != "":
		headers.append("Content-Type: application/json")
	# A POST carries the key in its JSON body. DELETE has no body, so the
	# server accepts it from this header instead -- and requires it either way.
	# The same value is reused across retries, which is the entire point.
	if idempotency_key != "" and body == "":
		headers.append("Idempotency-Key: " + idempotency_key)

	var verb := HTTPClient.METHOD_GET if method == "GET" else HTTPClient.METHOD_POST
	if method == "DELETE":
		verb = HTTPClient.METHOD_DELETE

	var started := Time.get_ticks_msec()
	var err := req.request(base_url + path, headers, verb, body)
	if err != OK:
		req.queue_free()
		return {
			"transport_ok": false, "code": 0, "json": null, "headers": [],
			"elapsed_ms": 0,
			"detail": "HTTPRequest refused the call (err=%d)." % err,
		}

	var res: Array = await req.request_completed
	var elapsed := Time.get_ticks_msec() - started
	req.queue_free()

	if res[0] != HTTPRequest.RESULT_SUCCESS:
		return {
			"transport_ok": false, "code": 0, "json": null, "headers": res[2],
			"elapsed_ms": elapsed,
			"detail": "Transport result %d." % res[0],
		}

	var raw: PackedByteArray = res[3]
	return {
		"transport_ok": true,
		"code": res[1],
		"json": JSON.parse_string(raw.get_string_from_utf8()),
		"headers": res[2],
		"elapsed_ms": elapsed,
		"detail": "",
	}


# --- Online/offline tracking ---
#
# Offline is a designed state, not an error path. Callers render cached data
# behind a banner and disable Buy; they never show a live-looking control that
# is going to fail.

func _note_transport_failure() -> void:
	_consecutive_transport_failures += 1
	if _online:
		_online = false
		_log("offline")
		online_changed.emit(false)


func _note_transport_success() -> void:
	_consecutive_transport_failures = 0
	if not _online:
		_online = true
		_log("back online")
		online_changed.emit(true)


# --- Helpers ---

func _backoff(attempt: int) -> float:
	# Exponential with jitter. Jitter matters less here than in a fleet, but it
	# costs nothing and stops a retry storm if several calls fail together.
	var base: float = BACKOFF_BASE_SECONDS * pow(2.0, float(attempt - 1))
	var capped: float = minf(base, BACKOFF_MAX_SECONDS)
	return capped * randf_range(0.8, 1.2)


func _rate_limit_wait(headers: Array) -> float:
	for h in headers:
		var line := str(h)
		if line.to_lower().begins_with("x-ratelimit-reset:"):
			var value: String = line.split(":", true, 1)[1].strip_edges()
			if value.is_valid_float():
				return clampf(value.to_float(), 0.5, RATE_WAIT_MAX_SECONDS)
	return BACKOFF_BASE_SECONDS * 2.0


func _error_code(res: Dictionary) -> String:
	var j = res.get("json")
	if j is Dictionary:
		return str(j.get("error", "http_error"))
	return "http_error"


func _error_message(res: Dictionary) -> String:
	var j = res.get("json")
	if j is Dictionary and j.has("message"):
		return str(j["message"])
	return "The market rejected the request (HTTP %d)." % res.get("code", 0)


func _failure(code: String, message: String, http_code: int = 0,
		res: Dictionary = {}) -> Dictionary:
	return {
		"ok": false,
		"code": http_code,
		"json": res.get("json", null),
		"headers": res.get("headers", []),
		"elapsed_ms": res.get("elapsed_ms", 0),
		"error": code,
		"message": message,
	}


func _build_query(query: Dictionary) -> String:
	if query.is_empty():
		return ""
	var parts := PackedStringArray()
	for k in query.keys():
		var v = query[k]
		if v == null:
			continue
		parts.append("%s=%s" % [
			str(k).uri_encode(), str(v).uri_encode()
		])
	if parts.is_empty():
		return ""
	return "?" + "&".join(parts)


func _sleep(seconds: float) -> void:
	var tree := get_tree()
	if tree == null:
		return
	await tree.create_timer(seconds).timeout


func _mod_version() -> String:
	var main = Engine.get_meta("FleaMarketMain", null)
	if main != null and "VERSION" in main:
		return str(main.VERSION)
	return "0.0.0"


func _log(msg: String) -> void:
	print(LOG_PREFIX + msg)
